sudo: false
language: node_js
node_js:
- '0.10'
- '0.12'
- '4'
- '5'
- '6'
- iojs
before_script:
- npm install standard
- standard
script:
- npm install istanbul
- istanbul cover ./node_modules/.bin/_mocha --report lcovonly
after_script:
- npm install coveralls
- cat ./coverage/lcov.info | coveralls
